### ISSUE TITLE
Not sure is API work or not

### ISSUE THREAD

**Issue by Dm1Korneev** [txty-io/txty-cli#18]
Hey.
I have created project (41ec5eb1-1fcc-4dac-b373-6a5a67842d5e)
and export configuretion (9d52982c-ad3c-498c-b665-b02849f97b85)
set email and secret in .texterify.json

but get an error from the API:

![image](https://user-images.githubusercontent.com/7955306/121407713-47019580-c968-11eb-9da1-cb63a7a0ed57.png)

same if I open it in browser
Not sure what I am doing wrong

**Comment by chrztoph** [comment]
Hello,

I just noticed an issue in the documentation. The API is not located at `https://texterify.com/api` but rather at `https://app.texterify.com/api`. So try setting `"api_base_url": "https://app.texterify.com/api"` and let me know if it works.

I will fix the documentation.

**Comment by Dm1Korneev** [comment]
It works with this url. Thanks

**Comment by chrztoph** [comment]
Sorry for the inconveniences and great to hear it works now. 🙂
Thanks for making me aware of this issue.
